### ISSUE TITLE
dependencies conflict

### ISSUE THREAD

**Issue by sovetnik** [ascendbruce/awesome_rails_console#1]
Can you update this dependency?

```
Bundler could not find compatible versions for gem "byebug":
  In Gemfile:
    awesome_rails_console (>= 0) ruby depends on
      pry-byebug (>= 0) ruby depends on
        byebug (~> 1.1.1) ruby
    byebug (5.0.0)
```

**Comment by dars** [comment]
i have the same problem

**Comment by ascendbruce** [comment]
Hi @oblaka @dars, could you provide:
- your `Gemfile` (maybe in Gist)
- ruby version you are using (awesome_rails_console requires ruby 2.0 or above)
- awesome_rails_console version you are using (latest version is `0.2.1`)

I guess that you listed `byebug = 5.0.0` in `Gemfile`. But `pry-byebug 3.1.0` uses `byebug ~> 4.0`.

Since this gem is like a bunch of gems for convenience. If it was the case, I tend to not fixing it.

If you want to at least use `byebug 4.0.5`. Try:
- remove `awesome_rails_console` from `Gemfile`
- Update `Gemfile` to use `gem 'byebug', "~> 4.0"`
- Run `bundle install`
- Add `awesome_rails_console` back to `Gemfile`
- Run `bundle install` again

**Comment by abigure** [comment]
I encountered this situation with ruby 2.2.1 as well.

```
Bundler could not find compatible versions for gem "byebug":
  In snapshot (Gemfile.lock):
    byebug (= 6.0.2)

  In Gemfile:
    awesome_rails_console (>= 0) ruby depends on
      pry-byebug (>= 0) ruby depends on
        byebug (~> 1.1.1) ruby

    byebug (>= 0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by ascendbruce** [comment]
Hi @sovetnik, @dars and @abigure,

I've update this gem and remove `pry-byebug` dependency entirely. So this should no longer be an issue. Please update to version 0.3.0 and list your debugger in application `Gemfile` instead. Let me know if you still encounter issues. Thanks! :smile:
